# ------------------------------------------------ COMMENTS ------------------------------------------------------------
# Contains rountines to load the input data.


# -------------------------------------------- IMPORT MODULES ----------------------------------------------------------
import sys,os
import h5py

# ----------------------------------------------- FUNCTIONS ------------------------------------------------------------


def load_input_eliash_fortran():
    '''Load the input for the Eliashberg routine from output generated by the Fortran code'''
    return