# ------------------------------------------------ COMMENTS ------------------------------------------------------------
# Contains rountines to load the input data.


# -------------------------------------------- IMPORT MODULES ----------------------------------------------------------
import sys,os
import h5py
import w2dyn_aux
import Config as conf
import FourPoint as fp

# ----------------------------------------------- FUNCTIONS ------------------------------------------------------------


def load_input_eliash_fortran():
    '''Load the input for the Eliashberg routine from output generated by the Fortran code'''
    return

def load_1p_data(dga_conf: conf.DgaConfig = None):

    if(dga_conf.opt.g1_input_type == 'w2dyn'):
        # load contents from w2dynamics DMFT file:
        f1p = w2dyn_aux.w2dyn_file(fname=dga_conf.nam.input_path  + dga_conf.nam.fname_dmft)
        dmft1p = f1p.load_dmft1p_w2dyn()
        f1p.close()
        if (dmft1p['n'] == 0.0): dmft1p['n'] = 1.0 # WARNING: This is kinda a hack to fix some certain inputs. In general this might lead to problems.
    else:
        raise NotImplementedError('This method for obtaining g1 has not yet been implemented.')
    return dmft1p

def extract_gamma_w2dyn(dga_conf: conf.DgaConfig = None, giw_dmft=None, channel=None):


    g2_file = w2dyn_aux.g4iw_file(fname=dga_conf.nam.input_path + dga_conf.nam.fname_g2)

    # Load Green's function
    g2 = fp.LocalFourPoint(matrix=g2_file.read_g2_iw(channel=channel, iw=dga_conf.box.wn_core),channel=channel,
                                    beta=dga_conf.sys.beta, iw=dga_conf.box.wn_core)
    g2_file.close()

    # Clip them to the size needed:
    g2.cut_iv(niv_cut=dga_conf.box.niv_invbse)

    # Create generalized susceptibility:
    gchi = fp.LocalFourPoint(matrix=fp.vec_chir_from_g2(g2=g2,giw=giw_dmft), channel=g2.channel, beta=g2.beta, iw=g2.wn)

    # Extract gamma:
    chi0_urange = fp.LocalBubble(giw=giw_dmft, beta=g2.beta, niv_sum=dga_conf.box.niv_urange, iw=dga_conf.box.wn_core)
    gamma = fp.gammar_from_gchir(gchir=gchi, gchi0_urange=chi0_urange, u=dga_conf.sys.u)

    return gamma



def get_gamma_loc(dga_conf: conf.DgaConfig = None, giw_dmft=None):
    '''
        loads the local input file for the two-particle quantities and returns the local irreduzible vertex.
    '''

    # Load the data form specified file:
    if(dga_conf.opt.g2_input_type == 'w2dyn'):
        gamma_dens = extract_gamma_w2dyn(dga_conf = dga_conf, giw_dmft=giw_dmft, channel='dens')
        gamma_magn = extract_gamma_w2dyn(dga_conf = dga_conf, giw_dmft=giw_dmft, channel='magn')

    else:
        raise NotImplementedError('This method for obtaining g2 has not yet been implemented.')

    gamma_dens.cut_iv(niv_cut=dga_conf.box.niv_core)
    gamma_magn.cut_iv(niv_cut=dga_conf.box.niv_core)

    gamma_dmft = {
        'dens': gamma_dens,
        'magn': gamma_magn
    }

    return gamma_dmft
